language: node_js

node_js:
- "8.9.4"

before_install:
- npm install -g version-from-git
- version-from-git --travis

install:
- npm install

before_script:
- npm run build
- npm run build-test

script:
# Our tests currently don't run on Travis, disabling them for now
- npm --version

before_deploy:
- git config --local user.name "William Wong"
- git config --local user.email "compulim-npm-test@outlook.com"

deploy:
- provider: npm
  api_key: $NPM_TOKEN
  email: "compulim-npm-test@outlook.com"
  on:
    branch: ibiza
  skip_cleanup: true
  tag: ibiza

- provider: script
  script: bash scripts/deploycdn.sh
  skip_cleanup: true
  on:
    branch: ibiza
